const TATTOOERS = [
  {
    pp: "/pp/ilestlibre.jpg",
    insta: "https://www.instagram.com/il.est.libre/",
    nom: "il.est.libre",
    pays: "Belgique",
    ville: "Bruxelles",
    styles: "abstrait peinture freehand fineline réalisme blackwork",
  },
  {
    pp: "/pp/eraes.jpg",
    insta: "https://www.instagram.com/eraes_rock/",
    nom: "eRAeS",
    pays: "Belgique",
    ville: "Bruxelles",
    styles: "graphique blackwork",
  },
  {
    pp: "/pp/blum.jpg",
    insta: "https://www.instagram.com/blum.ttt/",
    nom: "Léah Blum",
    pays: "France",
    ville: "Paris",
    styles: "ornemental symétrique blackwork flash",
  },
  {
    pp: "/pp/caledonia.jpg",
    insta: "https://www.instagram.com/caledoniatattoo/",
    nom: "Caledonia",
    pays: "USA, État de Washington",
    ville: "Olympia",
    styles: "graphique colored",
  },
  {
    pp: "/pp/carloroffare.jpg",
    insta: "https://www.instagram.com/carloroffare/",
    nom: "Carlo Roffare",
    pays: "Belgique",
    ville: "Bruxelles",
    styles: "abstrait peinture freehand landscape blackwork",
  },
  {
    pp: "/pp/notilusse.jpg",
    insta: "https://www.instagram.com/no_tilusse_tattoo/",
    nom: "No Tilusse",
    pays: "France",
    ville: "Seine-et-Marne",
    styles: "aquarelle Disney colored",
  },
  {
    pp: "/pp/nanoponto.jpg",
    insta: "https://www.instagram.com/pontotattoo/",
    nom: "Nano Ponto",
    pays: "Argentine",
    ville: "Buenos Aires",
    styles: "handpoke micro landscape colored",
  },
  {
    pp: "/pp/doy.jpg",
    insta: "https://www.instagram.com/tattooist_doy/",
    nom: "Doy",
    pays: "Corée",
    ville: "Seoul",
    styles: "micro réalisme",
  },
  {
    pp: "/pp/tetimalik.jpg",
    insta: "https://www.instagram.com/tetimalik.tattoo/",
    nom: "Teti Malik",
    pays: "Allemagne",
    ville: "Dresde",
    styles: "abstrait blackwork",
  },
  {
    pp: "/pp/tan.jpg",
    insta: "https://www.instagram.com/_tan_tattoo/",
    nom: "Tan",
    pays: "Corée",
    ville: "Seoul",
    styles: "micro mignon fineline colored",
  },
  {
    pp: "/pp/janemiller.jpg",
    insta: "https://www.instagram.com/janemiller.ink/",
    nom: "Jane Miller",
    pays: "Allemagne",
    ville: "Berlin",
    styles: "anime colored",
  },
  {
    pp: "/pp/dasiek.jpg",
    insta: "https://www.instagram.com/dasiek.tattoo/",
    nom: "Dasiek Mikiciuk",
    pays: "Pologne",
    ville: "Poznyan",
    styles: "anime blackwork",
  },
  {
    pp: "/pp/tata.jpg",
    insta: "https://www.instagram.com/tattoogrossevilaine/",
    nom: "Tata",
    pays: "Belgique",
    ville: "Bruxelles",
    styles: "flash blackwork",
  },
  {
    pp: "/pp/melange.jpg",
    insta: "https://www.instagram.com/melange.tattoo/",
    nom: "Melange",
    pays: "Corée",
    ville: "Seoul",
    styles: "néojaponais bleu",
  },
  {
    pp: "/pp/alexaureo.jpg",
    insta: "https://www.instagram.com/alessandro_capozzi/",
    nom: "Alex Aureo",
    pays: "Italie",
    ville: "Rome",
    styles: "réalisme micro blackwork",
  },
  // {
  //   pp: "/pp/.jpg",
  //   insta: "",
  //   nom: "",
  //   pays: "",
  //   ville: "",
  //   styles: "",
  // },
];
